name: docker

on:
  push:
    branches:
      - 'main'
      - 'use-global-docker-workflow'
    tags:
      - 'v*'

jobs:
  docker:
    uses: onlydustxyz/cicd/.github/workflows/docker-workflow.yml@main
    with:
      docker_repository: od-badge-signup
      image_tag: ${{ github.ref_name }}
    secrets: inherit
