name: docker

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build:
    name: docker_build_and_push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      id: build-image
      env:
        DOCKER_REPOSITORY: od-badge-signup
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        IMAGE_TAG: ${{ github.ref_name }}
      run: |
        echo "Building docker image..."
        docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG .
        echo "::set-output name=image::$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG"

    - name: Push the image to Docker Hub
      id: push-image
      env:
        IMAGE: ${{ steps.build-image.outputs.image }}
      run: |
        echo "Pushing image to Docker Hub..."
        docker push $IMAGE
        echo "Pushed image $IMAGE to Docker Hub"
