name: docker

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  docker:
    uses: onlydustxyz/cicd/.github/workflows/docker-workflow.yml@main
    with:
      image_name: od-badge-signup
      image_tag: ${{ github.ref_name }}
      dockerfile: rocket-rs
      datadog_label: '[{"source": "deathnote", "service": "od-badge-signup"}]'
    secrets: inherit
