name: docker

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build:
    name: docker_build_and_push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: docker/login-action@v2
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      env:
        AWS_REGION: us-east-1

    - name: Build the Docker image
      id: build-image
      env:
        ECR_REGISTRY: public.ecr.aws/a3g2g4b8
        ECR_REPOSITORY: od-badge-signup
        IMAGE_TAG: ${{ github.ref_name }}
      run: |
        echo "Building docker image..."
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Push the image to Amazon ECR
      id: push-image
      env:
        IMAGE: ${{ steps.build-image.outputs.image }}
      run: |
        echo "Pushing image to ECR..."
        docker push $IMAGE
        echo "Pushed image $IMAGE to ECR"